name: Deploy to Hugging Face Space (Docker)

on:
  push:
    branches: [ "main" ]   # change if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install git-lfs
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Push to HF Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE: spaces/UtpalKumar/RecommendationSystem  # e.g. spaces/alex/my-ml-docker-space
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          # clone the Space repo
          rm -rf /tmp/space && mkdir -p /tmp/space
          git clone https://huggingface.co/$HF_SPACE /tmp/space

          # copy your repo contents into the Space (excluding .git)
          rsync -a --delete --exclude ".git" ./ /tmp/space/

          cd /tmp/space
          git add .
          git commit -m "CI: deploy from $GITHUB_REPOSITORY@${GITHUB_SHA::7}" || echo "No changes"

          # push using the token
          git push https://user:$HF_TOKEN@huggingface.co/$HF_SPACE HEAD:main
